from datetime import datetime
from app.database.model import ScanLog, User
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch
from docx import Document
from docx.shared import Inches
import os


# common config 
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LOGO_PATH = os.path.join(BASE_DIR, "static", "favicon (1).png")
FOOTER_TEXT = "This report generated by AI-POWERED WEB APPLICATION"


#  build data
def build_report_data(user_id):
    scan = ScanLog.query.filter_by(user_id=user_id)\
        .order_by(ScanLog.scan_date.desc())\
        .first()

    user = User.query.get(user_id)

    if not scan:
        return None

    risk_level = "LOW"
    if scan.total_quarantined > 0:
        risk_level = "HIGH"
    elif scan.total_suspicious > 0:
        risk_level = "MEDIUM"

    return {
        "user": user.user_name,
        "email": user.email,
        "scan_date": scan.scan_date.strftime("%Y-%m-%d %H:%M:%S"),
        "total_scanned": scan.total_scanned,
        "safe": scan.total_safe,
        "suspicious": scan.total_suspicious,
        "quarantined": scan.total_quarantined,
        "risk": risk_level
    }


# TXT REPORT
def generate_txt(report, filepath):
    content = f"""
AI EMAIL QUARANTINE – SCAN REPORT
--------------------------------

User Name       : {report['user']}
Email           : {report['email']}
Scan Date       : {report['scan_date']}

SUMMARY
-------
Total Scanned   : {report['total_scanned']}
Safe Emails     : {report['safe']}
Suspicious      : {report['suspicious']}
Quarantined     : {report['quarantined']}

RISK ASSESSMENT
---------------
Overall Risk    : {report['risk']}

Analyst Note:
-------------
This scan was performed using a machine learning based email
classification engine with threat intelligence integration.

Report Generated On: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

--------------------------------
{FOOTER_TEXT}
"""

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(content)


# DOCX REPORT
def generate_docx(report, filepath):
    doc = Document()
    doc.add_heading("AI Email Quarantine – Scan Report", level=1)

    doc.add_paragraph(f"User Name: {report['user']}")
    doc.add_paragraph(f"Email: {report['email']}")
    doc.add_paragraph(f"Scan Date: {report['scan_date']}")

    doc.add_heading("Scan Summary", level=2)
    doc.add_paragraph(f"Total Scanned: {report['total_scanned']}")
    doc.add_paragraph(f"Safe Emails: {report['safe']}")
    doc.add_paragraph(f"Suspicious Emails: {report['suspicious']}")
    doc.add_paragraph(f"Quarantined Emails: {report['quarantined']}")

    doc.add_heading("Risk Assessment", level=2)
    doc.add_paragraph(f"Overall Risk Level: {report['risk']}")

    doc.add_paragraph(
        "This report is generated for security auditing and incident review purposes."
    )

    # Footer with logo (Word-safe watermark approach)
    section = doc.sections[0]
    footer = section.footer
    footer_para = footer.paragraphs[0]
    footer_para.text = FOOTER_TEXT
    footer_para.italic = True

    if os.path.exists(LOGO_PATH):
        footer_para.add_run("\n")
        footer_para.add_run().add_picture(LOGO_PATH, width=Inches(1.5))

    doc.save(filepath)


# PDF REPORT (IMAGE WATERMARK)
def generate_pdf(report, filepath):
    styles = getSampleStyleSheet()
    doc = SimpleDocTemplate(filepath, pagesize=A4)
    elements = []

    # Logo watermark (centered)
    if os.path.exists(LOGO_PATH):
        watermark = Image(LOGO_PATH)
        watermark.drawHeight = 3 * inch
        watermark.drawWidth = 3 * inch
        watermark.hAlign = "CENTER"
        elements.append(watermark)
        elements.append(Spacer(1, 20))

    elements.append(Paragraph("<b>AI Email Quarantine – Scan Report</b>", styles["Title"]))
    elements.append(Spacer(1, 12))

    elements.append(Paragraph(f"User Name: {report['user']}", styles["Normal"]))
    elements.append(Paragraph(f"Email: {report['email']}", styles["Normal"]))
    elements.append(Paragraph(f"Scan Date: {report['scan_date']}", styles["Normal"]))

    elements.append(Spacer(1, 12))
    elements.append(Paragraph("<b>Scan Summary</b>", styles["Heading2"]))

    elements.append(Paragraph(f"Total Scanned: {report['total_scanned']}", styles["Normal"]))
    elements.append(Paragraph(f"Safe Emails: {report['safe']}", styles["Normal"]))
    elements.append(Paragraph(f"Suspicious Emails: {report['suspicious']}", styles["Normal"]))
    elements.append(Paragraph(f"Quarantined Emails: {report['quarantined']}", styles["Normal"]))

    elements.append(Spacer(1, 12))
    elements.append(Paragraph("<b>Risk Assessment</b>", styles["Heading2"]))
    elements.append(Paragraph(f"Overall Risk Level: {report['risk']}", styles["Normal"]))

    # Footer text
    elements.append(Spacer(1, 30))
    elements.append(Paragraph(f"<i>{FOOTER_TEXT}</i>", styles["Normal"]))

    doc.build(elements)
